### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 1)

### ISSUE THREAD

**Issue by yyaoshuai** [likyoo/Siam-NestedUNet#10]
INFO:root:STARTING Dataset Creation
INFO:root:STARTING Dataloading
/home/anaconda3/envs/p36/lib/python3.6/site-packages/torch/serialization.py:453: SourceChangeWarning: source code of class 'models.Models.SNUNet_ECAM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
  2%|▏         | 64/3000 [00:37<28:54,  1.69it/s]Traceback (most recent call last):
  File "/home/pythonProject/Siam-NestedUNet-master/eval.py", line 37, in <module>
    cd_preds.data.cpu().numpy().flatten()).ravel()
ValueError: not enough values to unpack (expected 4, got 1)

**Comment by likyoo** [comment]
I didn't get this error, but maybe you can refer [here](https://github.com/likyoo/Siam-NestedUNet/issues/8#issuecomment-846727841).

**Comment by ChengxiHAN** [comment]
Modify line 36  in eval.py can be used ：
        tn, fp, fn, tp = confusion_matrix(labels.data.cpu().numpy().flatten(),
                        cd_preds.data.cpu().numpy().flatten(),labels=[0,1]).ravel()
