### ISSUE TITLE
How to calculate the flops of an IFN network？

### ISSUE THREAD

**Issue by liudong315** [likyoo/Siam-NestedUNet#14]
Hello, author! I'm having problems calculating flops for IFN networks, how did you do it, please!

**Comment by likyoo** [comment]
具体什么问题呢？时间太久了，我也不太记得了。

**Comment by liudong315** [comment]
就是用的INF网络github公布的代码，我计算不了它的flops值，想问下你是怎么计算的。

**Comment by liudong315** [comment]
已经解决该问题，谢谢！
