### ISSUE TITLE
直接可视化CDD数据标签发现很多噪点

### ISSUE THREAD

**Issue by lsh1994** [likyoo/Siam-NestedUNet#16]
![2021-09-23 00-27-11屏幕截图](https://user-images.githubusercontent.com/14355014/134384040-a42f7de6-6bf4-48e4-bffa-abed61b1e66d.png)
![2021-09-23 00-28-08屏幕截图](https://user-images.githubusercontent.com/14355014/134384054-cbec5037-0efd-43a4-a45b-448d3d75d780.png)

感谢作者的工作！直接可视化CDD数据标签发现很多噪点，这个代码未处理是否影响评价结果？

**Comment by likyoo** [comment]
你好，我并没有发现/处理这种情况。请问这是哪个文件呢？

**Comment by Runist** [comment]
我在自己数据集的预测中，也出现了这些噪点

**Comment by likyoo** [comment]
关于数据的问题，我做的分析也比较有限。或许您可以联系一下数据集的[原作者]。(https://www.researchgate.net/publication/325470033_CHANGE_DETECTION_IN_REMOTE_SENSING_IMAGES_USING_CONDITIONAL_ADVERSARIAL_NETWORKS)

**Comment by likyoo** [comment]
关于数据的问题，我做的分析也比较有限。或许您可以联系一下数据集的[原作者](https://www.researchgate.net/publication/325470033_CHANGE_DETECTION_IN_REMOTE_SENSING_IMAGES_USING_CONDITIONAL_ADVERSARIAL_NETWORKS)。

**Comment by lsh1994** [comment]
![image](https://user-images.githubusercontent.com/14355014/135531715-ad8e8899-56ed-4766-87a3-cc98f35db932.png)

参考代码：
```python
from collections import Counter
out = cv2.imread(p_label, cv2.IMREAD_GRAYSCALE)
print(p_a,Counter(out.reshape(-1)))
```

**Comment by lsh1994** [comment]
> 关于数据的问题，我做的分析也比较有限。或许您可以联系一下数据集的[原作者](https://www.researchgate.net/publication/325470033_CHANGE_DETECTION_IN_REMOTE_SENSING_IMAGES_USING_CONDITIONAL_ADVERSARIAL_NETWORKS)。

如上

**Comment by lsh1994** [comment]
> 你好，我并没有发现/处理这种情况。请问这是哪个文件呢？

如上
