### ISSUE TITLE
Directly visualize the CDD data label and find a lot of noise

### ISSUE THREAD

**Issue by lsh1994** [likyoo/Siam-NestedUNet#20]
Does the unprocessed code affect the evaluation result?

![image](https://user-images.githubusercontent.com/14355014/135532877-95026917-4612-4f41-a909-fb9823d88c66.png)

![image](https://user-images.githubusercontent.com/14355014/135531715-ad8e8899-56ed-4766-87a3-cc98f35db932.png)

参考代码：
```python
from collections import Counter
out = cv2.imread(p_label, cv2.IMREAD_GRAYSCALE)
print(p_a,Counter(out.reshape(-1)))
```

(hope not to close other people's issues easily)

**Comment by likyoo** [comment]
![image](https://user-images.githubusercontent.com/44317497/135583602-1caffb5c-25d9-4bec-a4bd-4b287e464fb9.png)
![image](https://user-images.githubusercontent.com/44317497/135583757-26c69bd2-bf51-49e3-ad32-ac821e307a82.png)
你好，我按照你的方式打开并没有发现噪点。

**Comment by lsh1994** [comment]
Counter(out.reshape(-1)) 返回的结果呢？查看下标签中的词频？

![image](https://user-images.githubusercontent.com/14355014/135718470-8e30f16a-d50d-4eb1-bcb2-a202cf4255e6.png)

**Comment by likyoo** [comment]
很多数据集都有这样的情况，处理一下就可以
