### ISSUE TITLE
freeze_support()报错

### ISSUE THREAD

**Issue by zzz5y** [likyoo/Siam-NestedUNet#24]
你好，请问代码在运行过程中会出现这个报错是啥回事呢
INFO:root:GPU AVAILABLE? True
INFO:root:STARTING Dataset Creation
INFO:root:STARTING Dataloading
INFO:root:LOADING Model
INFO:root:STARTING training
INFO:root:SET model mode to train!
  0%|          | 0/500 [00:00<?, ?it/s]
代码跑到这个地方就报错了！！！

**Comment by likyoo** [comment]
可以提供更多报错信息吗

**Comment by zzz5y** [comment]
> 

非常感谢，现在解决了那个问题了，好像是windows系统需要if __name__=='__main__'，然后再用multiprocessing.freeze_support()就能运行了，但是还有一个问题！就这个train的num_workers在哪个函数里设置呢，非常抱歉问出这样的问题，！！！非常感谢回答。。。

**Comment by zzz5y** [comment]
> 可以提供更多报错信息吗

非常感谢，是windows系统和mac系统需要改一下，谢谢你的帮助
