### ISSUE TITLE
关于代码和paper

### ISSUE THREAD

**Issue by bsyyhpc** [likyoo/Siam-NestedUNet#26]
我有点迷啊，我是从nestedunet这篇论文上的链接找过来的，但是我看代码又好像是snunet这篇论文的，nestedunet的代码上传了一部分。这两篇论文应该都是你们一个实验室出的，snunet论文的代码为什么不另外放在一个仓库中呢

**Comment by likyoo** [comment]
看readme，nestedunet在另一个tag上
一个是会议版，一个是期刊版，期刊版在前者基础上做了一些延伸的工作
