### ISSUE TITLE
UserWarning: Implicit dimension choice for log_softmax has been deprecated in CPU mode

### ISSUE THREAD

**Issue by loviji** [likyoo/Siam-NestedUNet#4]
Hello @likyoo ,
I've runned train.py in Linux in CPU mode and get user userWarning
> epoch 0 info 832 - 848:  42%|████████████████████████▏                                 | 52/125 [26:33<37:16, 30.64s/it]^C
> Traceback (most recent call last):
> ion choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
>   logpt = F.log_softmax(input)

To fix this issue edited code in model.py file to
`logpt = F.log_softmax(input, dim=1)`

**Comment by likyoo** [comment]
Hi @loviji ,
Thank you for pointing it out.

**Comment by patrickhwood** [comment]
Same issue in utils/metrics.py.
