### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by zhijiejia** [likyoo/Siam-NestedUNet#5]
@likyoo , Thanks for your work.
The CD dataset is contains by two parts, Model and Real. Can you tell me what is the origin of data set Real. And I want to know what standard it uses to mark the change area.

**Comment by zhijiejia** [comment]
Thanks，I get it.
![image](https://user-images.githubusercontent.com/43838913/112711698-4cbd1280-8f05-11eb-9a10-7e18f128020c.png)

**Comment by likyoo** [comment]
@zhijiejia you are right :)
