### ISSUE TITLE
Can this model be used as an encoder?

### ISSUE THREAD

**Issue by nikhilbyte** [likyoo/Siam-NestedUNet#9]
Hello, I was working on a project where I'm required to encode two images for finding multiclass semantic difference between them. 
Can you please tell which one should I use(with Channel attention or without)? and what changes should i consider?

**Comment by likyoo** [comment]
Hi, @nikhilbyte 
I don't know the specifics of your data and tasks, but maybe you can do it by changing the last few layers of the model.
